apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../k8s
patchesStrategicMerge:
  - patch-ingress-no-tls.yaml
  - patch-auth-mongo-emptydir.yaml
  - patch-tickets-mongo-emptydir.yaml
  - patch-orders-mongo-emptydir.yaml
  - patch-payments-mongo-emptydir.yaml
  - patch-redis-emptydir.yaml
  - patch-delete-pvcs.yaml
