$patch: delete
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auth-mongo-pvc
---
$patch: delete
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tickets-mongo-pvc
---
$patch: delete
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-mongo-pvc
---
$patch: delete
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payments-mongo-pvc
---
$patch: delete
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expiration-redis-pvc
